// ISO 3166-1 alpha-2 country code → full country name
// EU member states + EEA + common trading partners

export const COUNTRY_NAMES: Record<string, string> = {
  // EU member states
  AT: 'Austria',
  BE: 'Belgium',
  BG: 'Bulgaria',
  CY: 'Cyprus',
  CZ: 'Czech Republic',
  DE: 'Germany',
  DK: 'Denmark',
  EE: 'Estonia',
  ES: 'Spain',
  FI: 'Finland',
  FR: 'France',
  GR: 'Greece',
  HR: 'Croatia',
  HU: 'Hungary',
  IE: 'Ireland',
  IT: 'Italy',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  LV: 'Latvia',
  MT: 'Malta',
  NL: 'Netherlands',
  PL: 'Poland',
  PT: 'Portugal',
  RO: 'Romania',
  SE: 'Sweden',
  SI: 'Slovenia',
  SK: 'Slovakia',
  // EEA / close EU associates
  GB: 'United Kingdom',
  CH: 'Switzerland',
  NO: 'Norway',
  IS: 'Iceland',
  LI: 'Liechtenstein',
  // Balkans & Eastern Europe
  TR: 'Turkey',
  UA: 'Ukraine',
  RS: 'Serbia',
  MD: 'Moldova',
  AL: 'Albania',
  BA: 'Bosnia and Herzegovina',
  ME: 'Montenegro',
  MK: 'North Macedonia',
  XK: 'Kosovo',
  BY: 'Belarus',
  RU: 'Russia',
  GE: 'Georgia',
  AM: 'Armenia',
  AZ: 'Azerbaijan',
  // Middle East & North Africa
  IL: 'Israel',
  SA: 'Saudi Arabia',
  AE: 'United Arab Emirates',
  QA: 'Qatar',
  KW: 'Kuwait',
  JO: 'Jordan',
  LB: 'Lebanon',
  EG: 'Egypt',
  MA: 'Morocco',
  TN: 'Tunisia',
  DZ: 'Algeria',
  LY: 'Libya',
  // Asia-Pacific
  CN: 'China',
  JP: 'Japan',
  KR: 'South Korea',
  IN: 'India',
  SG: 'Singapore',
  TH: 'Thailand',
  VN: 'Vietnam',
  TW: 'Taiwan',
  HK: 'Hong Kong',
  MY: 'Malaysia',
  ID: 'Indonesia',
  PH: 'Philippines',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  // Americas
  US: 'United States',
  CA: 'Canada',
  MX: 'Mexico',
  BR: 'Brazil',
  AR: 'Argentina',
  CL: 'Chile',
  CO: 'Colombia',
  PE: 'Peru',
  // Africa
  ZA: 'South Africa',
  NG: 'Nigeria',
  KE: 'Kenya',
  ET: 'Ethiopia',
  GH: 'Ghana',
  TZ: 'Tanzania',
  // Oceania
  AU: 'Australia',
  NZ: 'New Zealand',
};
